### ISSUE TITLE
wrong smbios vendor and version?

### ISSUE THREAD

**Issue by draeath** [system76/thelio-io-windows#7]
Before I submit a PR, I wanted to confirm this is an issue with my specific system due to flashing my BIOS, and not something else.

----

While writing a patch to bring support parity /w the system76-power linux daemon, I ran into some odd behavior.

During some hardware troubleshooting after receiving my Thelio, I flashed the motherboard BIOS. After doing so, **on Linux, the correct 'system76' vendor and 'thelio-major-r2.1' version were reported in journalctl and the daemon ran the fans as expected.** However, since installing Windows and building/testing my patch, I found that it was receiving completely different data! Instead of the system76 OEM designations, the data was related to Gigabyte (board manufacturer).

I was easily able to add an additional patch so that I have functional fan control, but I'm wondering if the wrong smbioslib "fields" are being queried? (apologies if the terminology is wrong, this patch was actually my first exposure to rust!)

Expected:
  - `sys.manufacturer()`: 'system76'
  - `sys.version()`: 'thelio-major-r2.1'

Actual:
  - `sys.manufacturer()`: 'Gigabyte Technology Co., Ltd.'
  - `sys.version()`: '-CF'

My patches, for reference:
  - [Model support](https://github.com/draeath/thelio-io-windows/commit/3f6255cc41b4e66cae5ea00a8fd181ac9b0ea1c3) (this is what I planned to submit as a PR)
  - [My specific system](https://github.com/draeath/thelio-io-windows/commit/89d9aa77d2a635f5102da34d18fc66645db679f3) (what concerns me is that this is required to actually work on my system)

If it is useful (ie to look at the hardware configuration as shipped), I can provide an order number or serial number.

**Comment by draeath** [comment]
Really hoping for some feedback on this :(

@jackpot51 sorry for the ping, but is this fine here or should I go open a ticket instead?

**Comment by draeath** [comment]
Minor update: using a Pop!_OS 21.04 liveCD to troubleshoot something else for support, I found that system76-daemon in that version doesn't like my system there either, contrary to my initial confirmation. I see the following in that environment:

    system76-daemon[18352]: 2021-12-12 05:10:51,490  WARNING  invalid sys_vendor: 'Gigabyte Technology Co., Ltd.'
    system76-daemon[18352]: 2021-12-12 05:10:51,490  INFO  model: None

**Comment by leviport** [comment]
>During some hardware troubleshooting after receiving my Thelio, I flashed the motherboard BIOS. 

Was this with Gigabyte or System76 firmware? If the former, the Support team will be able to get you a USB image with System76 firmware which will have the proper DMI values. For further explanation, these DMI values are baked into the firmware, so if Gigabyte BIOS is installed, the motherboard will no longer be identified as a System76 product.

**Comment by draeath** [comment]
Yep, support is getting me hooked up with the correct image.

Once I have that confirmed to be working as expected I'll submit that PR.
